apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drm04.web.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drm04.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drm04.ai.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drm04.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai